# Generated by Django 4.1.2 on 2023-01-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lokasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=30, null=True)),
                ("alamat", models.TextField(max_length=50, null=True)),
                ("wpp", models.CharField(max_length=30, null=True)),
                ("provinsi", models.CharField(max_length=30, null=True)),
                ("golongan", models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
