# Generated by Django 4.1.2 on 2023-01-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portz_apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("desc", models.TextField(max_length=100, null=True)),
                ("prov", models.CharField(max_length=30, null=True)),
                ("pict", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
